version: '3.2'
services:
  opencv:
    build:
      context: './docker/'
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    tty: true
    working_dir: /home/opencv
    volumes:
      - ./src/:/home/opencv
    container_name: opencv
