version: '3.2'
services:
  opencv:
    build:
      context: './docker/'
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    tty: true
    working_dir: /home/opencv
    volumes:
      - ./src/:/home/opencv
      - ./build.sh:/usr/local/bin/build
    container_name: opencv
    ports:
      - 8888:8888
    environment:
      - PYTHON_VERSION=${PYTHON_VERSION}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      # - DISPLAY=`ifconfig en0 inet | grep inet | awk '{print $2}'`:0
